/**
 * @file    adc_manager.c
 * @brief   ADC Manager Module Implementation
 * @author  Embedded Systems Architect
 * @version 1.0.0
 * 
 * ============================================================================
 * OFFLINE WORKSTATION NOTE:
 * Because we cannot use STM32CubeMX to generate initialization code, this file
 * contains complete manual register-level and HAL-level configurations for the
 * ADC and GPDMA peripherals. Every clock, GPIO, and DMA setting is explicitly
 * defined here.
 * ============================================================================
 */

#include "adc_manager.h"
#include "filter.h"
#include "stm32u5xx_hal.h"

/* ============================================================================
 * PRIVATE VARIABLES
 * ============================================================================
 */

/**
 * @brief ADC Handle Structure
 * 
 * This structure holds all configuration and state for ADC1.
 * Normally generated by CubeMX, we manually populate it.
 */
ADC_HandleTypeDef hadc1 = {0};

/**
 * @brief DMA Handle for ADC
 * 
 * GPDMA1 Channel 0 is dedicated to ADC1.
 */
DMA_HandleTypeDef hdma_adc1 = {0};

/**
 * @brief DMA Circular Double Buffer
 * 
 * Why 64 elements? 
 * 4 channels × 16 samples per channel = 64 total elements.
 * This gives us 16 complete sets of 4 channel readings.
 * At 20kSPS, this buffer represents ~3.2ms of history.
 */
static uint16_t adc_dma_buffer[ADC_DMA_BUFFER_SIZE];

/**
 * @brief Index tracker for double-buffering
 * 
 * When DMA Half-Transfer interrupt fires, the first half is ready.
 * When Full-Transfer fires, the second half is ready.
 * We use this flag to know which half to process.
 */
static volatile uint8_t adc_active_half = 0;

/**
 * @brief Latest raw ADC readings
 * 
 * Populated by the ADC task after processing DMA buffer.
 * Volatile because it's accessed by DMA ISR and task context.
 */
static volatile ADC_RawData_t adc_latest_raw = {0};

/**
 * @brief Calibration data
 * 
 * Default calibration assumes ideal signal conditioning.
 * Update via ADC_Calibrate() routine.
 */
static ADC_Calibration_t adc_calibration = {
    .load_cell_zero = 2048,
    .load_cell_scale = (FORCE_PHYSICAL_RANGE / FORCE_ADC_HALF_RANGE),
    .knee_angle_zero = 2048,
    .knee_angle_scale = (KNEE_ANGLE_PHYSICAL_RANGE / KNEE_ANGLE_ADC_HALF_RANGE),
    .moment_zero = 2048,
    .moment_scale = (MOMENT_PHYSICAL_RANGE / MOMENT_ADC_HALF_RANGE),
    .battery_scale = ((float)BATTERY_MAX_VOLTAGE_MV / (float)BATTERY_ADC_MAX)
};

/* ============================================================================
 * PRIVATE FUNCTION PROTOTYPES
 * ============================================================================
 */
static void ADC_ConfigGPIO(void);
static void ADC_ConfigDMA(void);
static void ADC_ProcessHalfBuffer(uint16_t *start_ptr, uint16_t count);

/* ============================================================================
 * PUBLIC FUNCTION IMPLEMENTATIONS
 * ============================================================================
 */

/**
 * @brief Initialize ADC1 with DMA
 * 
 * MANUAL INIT SEQUENCE:
 * 1. Configure ADC input GPIOs as analog
 * 2. Configure GPDMA1 Channel 0
 * 3. Configure ADC1 parameters
 * 4. Link DMA handle to ADC handle
 * 5. Calibrate ADC (removes internal offset errors)
 */
HAL_StatusTypeDef ADC_Init(void)
{
    /* Step 1: Configure GPIO pins for analog input */
    ADC_ConfigGPIO();

    /* Step 2: Configure DMA for circular buffer */
    ADC_ConfigDMA();

    /* Step 3: Configure ADC1 */
    hadc1.Instance = ADC1;
    hadc1.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV4; /* 80MHz/4 = 20MHz ADC clock */
    hadc1.Init.Resolution = ADC_RESOLUTION_12B;
    hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
    hadc1.Init.ScanConvMode = ADC_SCAN_ENABLE;
    hadc1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
    hadc1.Init.LowPowerAutoWait = DISABLE;
    hadc1.Init.ContinuousConvMode = ENABLE; /* Run continuously */
    hadc1.Init.NbrOfConversion = ADC_NUM_CHANNELS;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START; /* We start it, not a timer */
    hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.DMAContinuousRequests = ENABLE; /* Keep DMA requesting after each conversion */
    hadc1.Init.Overrun = ADC_OVR_DATA_OVERWRITTEN; /* Don't stop on overrun */
    hadc1.Init.OversamplingMode = ENABLE;
    
    /* Oversampling config: 16x oversampling, right shifted by 4 bits */
    hadc1.Init.Oversampling.Ratio = ADC_OVERSAMPLING_RATIO_16X;
    hadc1.Init.Oversampling.RightBitShift = ADC_RIGHTBITSHIFT_4;
    hadc1.Init.Oversampling.TriggeredMode = ADC_TRIGGEREDMODE_SINGLE_TRIGGER;
    hadc1.Init.Oversampling.OversamplingStopReset = ADC_REGOVERSAMPLING_CONTINUES_MODE;

    if (HAL_ADC_Init(&hadc1) != HAL_OK)
    {
        return HAL_ERROR;
    }

    /* Step 3.1: Configure each ADC channel */
    ADC_ChannelConfTypeDef sConfig = {0};
    
    /* Channel 5: Load Cell (PA0) */
    sConfig.Channel = ADC_CHANNEL_5;
    sConfig.Rank = ADC_RANK_1;
    sConfig.SamplingTime = ADC_SAMPLETIME_247CYCLES_5;
    sConfig.SingleDiff = ADC_SINGLE_ENDED;
    sConfig.OffsetNumber = ADC_OFFSET_NONE;
    sConfig.Offset = 0;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) return HAL_ERROR;

    /* Channel 6: Knee Angle (PA1) */
    sConfig.Channel = ADC_CHANNEL_6;
    sConfig.Rank = ADC_RANK_2;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) return HAL_ERROR;

    /* Channel 7: Moment (PA2) */
    sConfig.Channel = ADC_CHANNEL_7;
    sConfig.Rank = ADC_RANK_3;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) return HAL_ERROR;

    /* Channel 8: Battery (PA3) */
    sConfig.Channel = ADC_CHANNEL_8;
    sConfig.Rank = ADC_RANK_4;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) return HAL_ERROR;

    /* Step 4: Run internal ADC calibration (critical for accuracy) */
    /* This compensates for internal capacitor mismatches */
    if (HAL_ADCEx_Calibration_Start(&hadc1, ADC_CALIB_OFFSET_LINEARITY, ADC_SINGLE_ENDED) != HAL_OK)
    {
        return HAL_ERROR;
    }

    return HAL_OK;
}

/**
 * @brief Start ADC DMA continuous conversion
 */
HAL_StatusTypeDef ADC_StartDMA(void)
{
    /* 
     * Start continuous DMA transfer.
     * Length is total buffer size (64 elements).
     * DMA will wrap around automatically (circular mode).
     */
    return HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_dma_buffer, ADC_DMA_BUFFER_SIZE);
}

/**
 * @brief Get raw ADC values
 */
HAL_StatusTypeDef ADC_GetRawValue(ADC_RawData_t *raw_data)
{
    if (raw_data == NULL) return HAL_ERROR;
    
    /* Critical section - copy volatile data atomically */
    taskENTER_CRITICAL();
    raw_data->load_cell_raw = adc_latest_raw.load_cell_raw;
    raw_data->knee_angle_raw = adc_latest_raw.knee_angle_raw;
    raw_data->moment_raw = adc_latest_raw.moment_raw;
    raw_data->battery_raw = adc_latest_raw.battery_raw;
    taskEXIT_CRITICAL();
    
    return HAL_OK;
}

/**
 * @brief Get filtered and normalized values
 */
HAL_StatusTypeDef ADC_GetFilteredValue(ADC_FilteredData_t *filtered_data)
{
    if (filtered_data == NULL) return HAL_ERROR;
    
    ADC_RawData_t raw;
    ADC_GetRawValue(&raw);
    
    /* Apply filters to each channel */
    int16_t f_force = ADC_ApplyFilter(0, raw.load_cell_raw);
    int16_t f_angle = ADC_ApplyFilter(1, raw.knee_angle_raw);
    int16_t f_moment = ADC_ApplyFilter(2, raw.moment_raw);
    int16_t f_batt = ADC_ApplyFilter(3, raw.battery_raw);
    
    /* Convert to physical units using calibration data */
    /* Formula: Physical = (Raw - Zero) * Scale */
    filtered_data->force = (int16_t)((f_force - adc_calibration.load_cell_zero) * adc_calibration.load_cell_scale);
    filtered_data->knee_angle = (int16_t)((f_angle - adc_calibration.knee_angle_zero) * adc_calibration.knee_angle_scale);
    filtered_data->moment = (int16_t)((f_moment - adc_calibration.moment_zero) * adc_calibration.moment_scale);
    filtered_data->battery_mv = (uint16_t)(f_batt * adc_calibration.battery_scale);
    
    /* Clamp values to valid ranges (safety) */
    if (filtered_data->force < FORCE_MIN_VALID) filtered_data->force = FORCE_MIN_VALID;
    if (filtered_data->force > FORCE_MAX_VALID) filtered_data->force = FORCE_MAX_VALID;
    
    if (filtered_data->knee_angle < KNEE_ANGLE_MIN_VALID) filtered_data->knee_angle = KNEE_ANGLE_MIN_VALID;
    if (filtered_data->knee_angle > KNEE_ANGLE_MAX_VALID) filtered_data->knee_angle = KNEE_ANGLE_MAX_VALID;
    
    if (filtered_data->moment < MOMENT_MIN_VALID) filtered_data->moment = MOMENT_MIN_VALID;
    if (filtered_data->moment > MOMENT_MAX_VALID) filtered_data->moment = MOMENT_MAX_VALID;
    
    return HAL_OK;
}

/**
 * @brief Apply selected filter
 */
int16_t ADC_ApplyFilter(uint8_t channel, int16_t raw_value)
{
    if (channel >= ADC_NUM_CHANNELS) return raw_value;
    
#if (ACTIVE_FILTER_TYPE == FILTER_TYPE_IIR)
    return Filter_ApplyIIR(&iir_filters[channel], raw_value);
#elif (ACTIVE_FILTER_TYPE == FILTER_TYPE_MOVING_AVG)
    return Filter_ApplyMovingAvg(&ma_filters[channel], raw_value);
#else
    return Filter_ApplyKalman(&kalman_filters[channel], raw_value);
#endif
}

/**
 * @brief Validate ADC data
 */
bool ADC_IsDataValid(const ADC_RawData_t *raw_data)
{
    if (raw_data == NULL) return false;
    
    /* Check for short circuits (too low) or open circuits (too high) */
    if ((raw_data->load_cell_raw < ADC_MIN_RAW) || (raw_data->load_cell_raw > ADC_MAX_RAW)) return false;
    if ((raw_data->knee_angle_raw < ADC_MIN_RAW) || (raw_data->knee_angle_raw > ADC_MAX_RAW)) return false;
    if ((raw_data->moment_raw < ADC_MIN_RAW) || (raw_data->moment_raw > ADC_MAX_RAW)) return false;
    if ((raw_data->battery_raw < ADC_MIN_RAW) || (raw_data->battery_raw > ADC_MAX_RAW)) return false;
    
    return true;
}

HAL_StatusTypeDef ADC_Calibrate(void) { return HAL_OK; } /* Placeholder */
uint16_t ADC_GetBufferFullness(void) { return ADC_DMA_BUFFER_SIZE; } /* Placeholder */

/* ============================================================================
 * PRIVATE FUNCTION IMPLEMENTATIONS
 * ============================================================================
 */

/**
 * @brief Configure ADC GPIO pins as Analog
 * 
 * Analog mode disconnects digital input Schmitt triggers,
 * reducing power consumption and preventing digital noise.
 */
static void ADC_ConfigGPIO(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    
    /* Enable GPIOA clock (already done in main, but safe to repeat) */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    
    /* Configure PA0, PA1, PA2, PA3 */
    GPIO_InitStruct.Pin = ADC_LOAD_CELL_PIN | ADC_KNEE_ANGLE_PIN | 
                          ADC_MOMENT_PIN | ADC_BATTERY_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;       /* Analog mode */
    GPIO_InitStruct.Pull = GPIO_NOPULL;            /* No pull-ups/downs for analog */
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

/**
 * @brief Configure GPDMA1 for ADC circular transfer
 * 
 * GPDMA (General Purpose DMA) on STM32U5 is more complex than legacy DMA.
 * We must configure:
 * - Source address (ADC data register)
 * - Destination address (our SRAM buffer)
 * - Data width (16-bit for ADC)
 * - Block/transfer counts
 * - Circular mode flag
 */
static void ADC_ConfigDMA(void)
{
    /* Ensure GPDMA1 clock is enabled */
    __HAL_RCC_GPDMA1_CLK_ENABLE();
    
    /* Clear any pending DMA flags */
    __HAL_GPDMA1_CLEAR_FLAG(GPDMA1_CHANNEL0, GPDMA_FLAG_TC | GPDMA_FLAG_HT | GPDMA_FLAG_TE);
    
    hdma_adc1.Instance = GPDMA1_CHANNEL0;
    hdma_adc1.Init.Request = GPDMA_REQUEST_ADC1;
    hdma_adc1.Init.Direction = DMA_PERIPH_TO_MEMORY;
    hdma_adc1.Init.Permalink = DMA_PERIPHERAL;
    hdma_adc1.Init.BlkHWRequest = DMA_BK_HWREQUEST_SINGLEBURST;
    hdma_adc1.Init.DataAlignment = DMA_DATAALIGN_HALFWORD; /* 16-bit ADC data */
    hdma_adc1.Init.SrcBurstLength = 1;  /* Read 1 half-word at a time */
    hdma_adc1.Init.DestBurstLength = 1; /* Write 1 half-word at a time */
    hdma_adc1.Init.SrcInc = DMA_PINC_DISABLE;   /* ADC DR address is fixed */
    hdma_adc1.Init.DestInc = DMA_MINC_ENABLE;   /* Increment SRAM buffer pointer */
    hdma_adc1.Init.Priority = DMA_HIGH_PRIORITY;
    
    /* Circular mode is set via the Linked List Node configuration on U5 */
    /* For HAL simplified mode, we use standard circular init if available, 
       otherwise standard mode requires re-triggering. We use HAL standard circular wrapper */
    hdma_adc1.Init.Mode = DMA_NORMAL; /* U5 GPDMA uses LLI for circular, but HAL abstracts this */
    
    /* Link DMA handle to ADC handle BEFORE HAL_ADC_Init */
    __HAL_LINKDMA(&hadc1, DMA_Handle, hdma_adc1);
    
    if (HAL_DMA_Init(&hdma_adc1) != HAL_OK)
    {
        Error_Handler();
    }
    
    /* Enable DMA Interrupts */
    HAL_NVIC_SetPriority(GPDMA1_Channel0_IRQn, 5, 0); /* Priority 5 - below configMAX_SYSCALL_INTERRUPT_PRIORITY */
    HAL_NVIC_EnableIRQ(GPDMA1_Channel0_IRQn);
}

/* ============================================================================
 * DMA CALLBACKS
 * ============================================================================ */

/**
 * @brief ADC DMA Half Transfer Complete Callback
 * 
 * Called when DMA has filled the FIRST HALF of the buffer.
 * We can safely process the first half while the second half fills.
 */
void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        /* Process first 32 elements (8 complete scans of 4 channels) */
        ADC_ProcessHalfBuffer(&adc_dma_buffer[0], ADC_DMA_BUFFER_SIZE / 2);
    }
}

/**
 * @brief ADC DMA Full Transfer Complete Callback
 * 
 * Called when DMA has filled the ENTIRE buffer and wrapped to start.
 * We can safely process the second half.
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        /* Process second 32 elements */
        ADC_ProcessHalfBuffer(&adc_dma_buffer[ADC_DMA_BUFFER_SIZE / 2], ADC_DMA_BUFFER_SIZE / 2);
    }
}

/**
 * @brief Process a half of the DMA buffer
 * 
 * This function averages the multiple samples in the half-buffer
 * to produce a single raw reading per channel.
 * 
 * @param start_ptr Pointer to start of the half-buffer
 * @param count Number of elements in this half
 */
static void ADC_ProcessHalfBuffer(uint16_t *start_ptr, uint16_t count)
{
    uint32_t sum_ch5 = 0, sum_ch6 = 0, sum_ch7 = 0, sum_ch8 = 0;
    uint16_t num_scans = count / ADC_NUM_CHANNELS;
    
    /* Sum all samples for each channel */
    for (uint16_t i = 0; i < num_scans; i++)
    {
        sum_ch5 += start_ptr[(i * ADC_NUM_CHANNELS) + 0]; /* CH5 */
        sum_ch6 += start_ptr[(i * ADC_NUM_CHANNELS) + 1]; /* CH6 */
        sum_ch7 += start_ptr[(i * ADC_NUM_CHANNELS) + 2]; /* CH7 */
        sum_ch8 += start_ptr[(i * ADC_NUM_CHANNELS) + 3]; /* CH8 */
    }
    
    /* Average and store */
    taskENTER_CRITICAL();
    adc_latest_raw.load_cell_raw  = (int16_t)(sum_ch5 / num_scans);
    adc_latest_raw.knee_angle_raw = (int16_t)(sum_ch6 / num_scans);
    adc_latest_raw.moment_raw     = (int16_t)(sum_ch7 / num_scans);
    adc_latest_raw.battery_raw    = (int16_t)(sum_ch8 / num_scans);
    taskEXIT_CRITICAL();
}
