/**
 * @file    FreeRTOSConfig.h
 * @brief   FreeRTOS Configuration for STM32U585 Cortex-M33
 * 
 * OFFLINE WORKSTATION CONSTRAINT:
 * Normally generated by CubeMX. This is manually crafted based on
 * STM32U5 Cortex-M33 requirements and our specific task architecture.
 */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

/* ============================================================================
 * BASIC CONFIGURATION
 * ============================================================================
 */
#define configUSE_PREEMPTION                    1   /* Preemptive scheduler */
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1   /* Assembly optimized next-task selection */
#define configUSE_TICKLESS_IDLE                 0   /* Keep simple for now */
#define configCPU_CLOCK_HZ                      160000000UL /* 160 MHz */
#define configTICK_RATE_HZ                      ((TickType_t)1000) /* 1ms tick */
#define configMAX_PRIORITIES                    7   /* 0-6, we use 1-6 */
#define configMINIMAL_STACK_SIZE                ((uint16_t)128) /* Words, not bytes */
#define configTOTAL_HEAP_SIZE                   ((size_t)(30 * 1024)) /* 30 KB heap */
#define configMAX_TASK_NAME_LEN                 16
#define configUSE_16_BIT_TICKS                  0   /* Use 32-bit ticks */
#define configIDLE_SHOULD_YIELD                 1
#define configUSE_TASK_NOTIFICATIONS            1   /* Lightweight sync */
#define configTASK_NOTIFICATION_ARRAY_ENTRIES   1
#define configQUEUE_REGISTRY_SIZE               8
#define configUSE_QUEUE_SETS                    0
#define configUSE_TIME_SLICING                  1
#define configUSE_NEWLIB_REENTRANT              0
#define configENABLE_BACKWARD_COMPATIBILITY     0
#define configNUM_THREAD_LOCAL_STORAGE_POINTERS 5

/* ============================================================================
 * MEMORY ALLOCATION
 * ============================================================================
 * We use heap_4.c (coalescing free memory) as defined in project constraints.
 */
#define configSUPPORT_STATIC_ALLOCATION         0
#define configSUPPORT_DYNAMIC_ALLOCATION        1
#define configAPPLICATION_ALLOCATED_HEAP        0

/* ============================================================================
 * HOOK FUNCTIONS
 * ============================================================================
 */
#define configUSE_IDLE_HOOK                     0
#define configUSE_TICK_HOOK                     0
#define configCHECK_FOR_STACK_OVERFLOW          2   /* Method 2: Extensive check */
#define configUSE_MALLOC_FAILED_HOOK            1

/* ============================================================================
 * RUNTIME STATS & TRACING
 * ============================================================================
 */
#define configGENERATE_RUN_TIME_STATS           0
#define configUSE_TRACE_FACILITY                1
#define configUSE_STATS_FORMATTING_FUNCTIONS    0

/* ============================================================================
 * CORTEX-M33 SPECIFIC SETTINGS (CRITICAL)
 * ============================================================================
 * 
 * SYSTICK:
 * FreeRTOS uses SysTick by default for its timer. This aligns perfectly
 * with our Bypass Mechanism where we stripped HAL_IncTick() out of the
 * SysTick_Handler and replaced it with xPortSysTickHandler().
 * 
 * PENDSV & SVC:
 * Context switching uses PendSV. First task start uses SVC.
 * 
 * MAX SYSCALL INTERRUPT PRIORITY:
 * This is THE MOST CRITICAL SETTING for DMA integration.
 * 
 * ARM Cortex-M priority logic is inverted: 0 is highest, 255 is lowest.
 * FreeRTOS requires that any interrupt calling FreeRTOS API (FromISR)
 * MUST have a numerical priority value GREATER THAN OR EQUAL TO
 * configMAX_SYSCALL_INTERRUPT_PRIORITY.
 * 
 * We set our DMA and UART interrupts to priority 5 and 6.
 * We set configMAX_SYSCALL_INTERRUPT_PRIORITY to 5.
 * This means priority 5, 6, 7... can safely call xQueueSendFromISR.
 * Priorities 0, 1, 2, 3, 4 CANNOT call FreeRTOS APIs.
 */
#define configPRIO_BITS                         4   /* STM32U5 uses 4 bits (16 levels) */

/* Map FreeRTOS priority to ARM priority */
#define configLIBRARY_LOWEST_INTERRUPT_PRIORITY         15
#define configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY     5
#define configKERNEL_INTERRUPT_PRIORITY                  ( configLIBRARY_LOWEST_INTERRUPT_PRIORITY << (8 - configPRIO_BITS) )
#define configMAX_SYSCALL_INTERRUPT_PRIORITY            ( configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY << (8 - configPRIO_BITS) )

/* ============================================================================
 * SOFTWARE TIMER CONFIGURATION
 * ============================================================================
 */
#define configUSE_TIMERS                        1
#define configTIMER_TASK_PRIORITY                2
#define configTIMER_QUEUE_LENGTH                 10
#define configTIMER_TASK_STACK_DEPTH             (configMINIMAL_STACK_SIZE * 2)

/* ============================================================================
 * INTERRUPT HANDLER MACROS (ARM_CM33_NTZ PORT SPECIFIC)
 * ============================================================================
 * These tell the portable layer which functions to call for context switching.
 * They MUST match the overrides we placed in stm32u5xx_it.c.
 */
#define vPortSVCHandler     SVC_Handler
#define xPortPendSVHandler  PendSV_Handler
#define xPortSysTickHandler SysTick_Handler

/* ============================================================================
 * OPTIONAL ASSERTIONS & DEBUGGING
 * ============================================================================
 */
#define configASSERT(x) if ((x) == 0) { taskDISABLE_INTERRUPTS(); for(;;); }

/* Map standard library functions for FreeRTOS */
#define vPortYield()        portYIELD()
#define vPortYieldFromISR() portYIELD_FROM_ISR()

#endif /* FREERTOS_CONFIG_H */
